<?php

echo "<!doctype html>\n";
echo "<!--[if IE 9]> <html class=\"no-js ie9 fixed-layout\" lang=\"en\"> <![endif]-->\n";
echo "<!--[if gt IE 9]><!--> <html class=\"no-js \" lang=\"en\"> <!--<![endif]-->\n";
echo "<head>\n";
echo "<script>\n";
echo "function showHint(str) {\n";
echo "    if (str.length == 0) {\n";
echo "        document.getElementById(\"txtHint\").innerHTML = \"\";\n";
echo "        return;\n";
echo "    } else {\n";
echo "        var xmlhttp = new XMLHttpRequest();\n";
echo "        xmlhttp.onreadystatechange = function() {\n";
echo "            if (this.readyState == 4 && this.status == 200) {\n";
echo "                document.getElementById(\"txtHint\").innerHTML = this.responseText;\n";
echo "            }\n";
echo "        }\n";
echo "        xmlhttp.open(\"GET\", \"gethint.php?q=\"+str, true);\n";
echo "        xmlhttp.send();\n";
echo "    }\n";
echo "}\n";
echo "</script>\n";
echo "    <!-- Basic -->\n";
echo "    <meta charset=\"utf-8\">\n";
echo "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n";
echo "    \n";
echo "    <!-- Mobile Meta -->\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no\">\n";
echo "    \n";
echo "    <!-- Site Meta -->\n";
echo "    <title>Face emotion recognition</title>\n";
echo "    <meta name=\"keywords\" content=\"\">\n";
echo "    <meta name=\"description\" content=\"\">\n";
echo "    <meta name=\"author\" content=\"\">\n";
echo "    \n";
echo "    <!-- Site Icons -->\n";
echo "    <link rel=\"shortcut icon\" href=\"#\" type=\"image/x-icon\" />\n";
echo "    <link rel=\"apple-touch-icon\" href=\"images/apple-touch-icon.png\">\n";
echo "\n";
echo "	<!-- Google Fonts -->\n";
echo "    <link href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,400i,500,700,900\" rel=\"stylesheet\"> \n";
echo "    <link href=\"https://fonts.googleapis.com/css?family=Droid+Serif:400,400i,700,700i\" rel=\"stylesheet\"> \n";
echo "	\n";
echo "    <!-- Custom & Default Styles -->\n";
echo "	<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\n";
echo "    <link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\n";
echo "    <link rel=\"stylesheet\" href=\"css/carousel.css\">\n";
echo "    <link rel=\"stylesheet\" href=\"css/animate.css\">\n";
echo "    <link rel=\"stylesheet\" href=\"style.css\">\n";
echo "\n";
echo "	<!--[if lt IE 9]>\n";
echo "		<script src=\"js/vendor/html5shiv.min.js\"></script>\n";
echo "		<script src=\"js/vendor/respond.min.js\"></script>\n";
echo "	<![endif]-->\n";
echo "<!video embeding html>\n";
echo "<head>\n";
echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
echo "<style>\n";
echo "* {\n";
echo "  box-sizing: border-box;\n";
echo "}\n";
echo "\n";
echo "body {\n";
echo "  margin: 0;\n";
echo "  font-family: Arial;\n";
echo "  font-size: 17px;\n";
echo "}\n";
echo "\n";
echo "#myVideo {\n";
echo "  position: fixed;\n";
echo "  right: 0;\n";
echo "  bottom: 0;\n";
echo "  min-width: 100%; \n";
echo "  min-height: 100%;\n";
echo "}\n";
echo "\n";
echo ".content {\n";
echo "  position: fixed;\n";
echo "  bottom: 0;\n";
echo "  background: rgba(0, 0, 0, 0.5);\n";
echo "  color: #f1f1f1;\n";
echo "  width: 100%;\n";
echo "  padding: 20px;\n";
echo "}\n";
echo "\n";
echo "#myBtn {\n";
echo "  width: 200px;\n";
echo "  font-size: 18px;\n";
echo "  padding: 10px;\n";
echo "  border: none;\n";
echo "  background: #000;\n";
echo "  color: #fff;\n";
echo "  cursor: pointer;\n";
echo "}\n";
echo "\n";
echo "#myBtn:hover {\n";
echo "  background: #ddd;\n";
echo "  color: black;\n";
echo "}\n";
echo "</style>\n";
echo "</head>\n";
echo "<body>\n";
echo "\n";
echo "<video autoplay muted loop id=\"myVideo\">\n";
echo "  <source src=\"preview.mp4\" type=\"video/mp4\">\n";
echo "  Your browser does not support HTML5 video.\n";
echo "</video>\n";
echo "\n";
echo "\n";
echo "\n";
echo "  \n";
echo "  \n";
echo "<script>\n";
echo "var video = document.getElementById(\"myVideo\");\n";
echo "var btn = document.getElementById(\"myBtn\");\n";
echo "\n";
echo "function myFunction() {\n";
echo "  if (video.paused) {\n";
echo "    video.play();\n";
echo "    btn.innerHTML = \"Pause\";\n";
echo "  } else {\n";
echo "    video.pause();\n";
echo "    btn.innerHTML = \"Play\";\n";
echo "  }\n";
echo "}\n";
echo "</script>\n";
echo "\n";
echo "</head>\n";
echo "<body>  \n";
echo "<!-- LOADER -->\n";
echo "    <div id=\"preloader\">\n";
echo "        <img class=\"preloader\" src=\"images/loader.gif\" alt=\"\">\n";
echo "    </div><!-- end loader -->\n";
echo "    <!-- END LOADER -->\n";
echo "\n";
echo "    <div id=\"wrapper\">\n";
echo "        <!-- BEGIN # MODAL LOGIN -->\n";
echo "        <div class=\"modal fade\" id=\"login-modal\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\" style=\"display: none;\">\n";
echo "            <div class=\"modal-dialog\">\n";
echo "                <div class=\"modal-content\">\n";
echo "                    <!-- Begin # DIV Form -->\n";
echo "                    <div id=\"div-forms\">\n";
echo "                        <form id=\"login-form\">\n";
echo "                            <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n";
echo "                                <span class=\"flaticon-add\" aria-hidden=\"true\"></span>\n";
echo "                            </button>\n";
echo "                            <div class=\"modal-body\">\n";
echo "                                <input class=\"form-control\" type=\"text\" placeholder=\"What you are looking for?\" onkeyup=\"showHint(this.value)\" required>\n";
echo "                            </div>\n";
echo "                        </form><!-- End # Login Form -->\n";
echo "                    </div><!-- End # DIV Form -->\n";
echo "                </div>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "        <!-- END # MODAL LOGIN -->\n";
echo "\n";
echo "\n";
echo "        <header class=\"header\">\n";
echo "            <div class=\"topbar clearfix\">\n";
echo "                <div class=\"container\">\n";
echo "                    <div class=\"row-fluid\">\n";
echo "                        <div class=\"col-md-6 col-sm-6 text-left\">\n";
echo "                                                    </div><!-- end left -->\n";
echo "                    </div><!-- end row -->\n";
echo "                </div><!-- end container -->\n";
echo "            </div><!-- end topbar -->\n";
echo "\n";
echo "            <div class=\"container\">\n";
echo "                <nav class=\"navbar navbar-default yamm\">\n";
echo "                    <div class=\"navbar-header\">\n";
echo "                        <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\" aria-controls=\"navbar\">\n";
echo "                            <span class=\"sr-only\">Toggle navigation</span>\n";
echo "                            <span class=\"icon-bar\"></span>\n";
echo "                            <span class=\"icon-bar\"></span>\n";
echo "                            <span class=\"icon-bar\"></span>\n";
echo "                        </button>\n";
echo "                        <div class=\"logo-normal\">\n";
echo "                            <a class=\"navbar-brand\" href=\"index.html\"><img src=\"#\" alt=\"\"></a>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "\n";
echo "\n";
echo "\n";
echo "\n";
echo "                    <div id=\"navbar\" class=\"navbar-collapse collapse\">\n";
echo "                        <ul class=\"nav navbar-nav navbar-right\">\n";
echo "                            <li><a href=\"index.html\">Home</a></li>\n";
echo "                            <li class=\"dropdown yamm-fw yamm-half\"><a href=\"#\" data-toggle=\"dropdown\" class=\"dropdown-toggle active\">Mega Menu <b class=\"fa fa-angle-down\"></b></a>\n";
echo "                                <ul class=\"dropdown-menu\">\n";
echo "                                    <li>\n";
echo "                                        <div class=\"yamm-content clearfix\">\n";
echo "                                            <div class=\"row-fluid\">\n";
echo "                                                <div class=\"col-md-6 col-sm-6\">\n";
echo "                                                                                                        <ul>\n";
echo "                                                        <li><a href=\"#\">Login</a></li>\n";
echo "<li><a href=\"http://127.0.0.1/form.php\">Signup</a></li>\n";
echo "\n";
echo "                                                                                                            </ul>\n";
echo "                                                </div>\n";
echo "                                                <div class=\"col-md-6 col-sm-6\">\n";
echo "                                                    <div class=\"menu-widget text-center\">\n";
echo "                                                                                      </div><!-- end widget -->\n";
echo "                                                </div>\n";
echo "                                            </div>\n";
echo "                                        </div>\n";
echo "                                    </li>\n";
echo "                                </ul>\n";
echo "                            </li>\n";
echo "                            <li><a href=\"blog-3.html\">Download</a></li>\n";
echo "<li class=\"iconitem\"><a href=\"#\" data-toggle=\"modal\" data-target=\"#login-modal\"><i class=\"fa fa-search\"></i></a></li>\n";
echo "\n";
echo "                                                            </ul>\n";
echo "                            </li>\n";
echo "                                </ul>\n";
echo "                            </li>\n";
echo "                            <ul class=\"nav navbar-nav navbar-right\">\n";
echo "                            <li><a href=\"page-contact.html\">Contact</a></li>\n";
echo "\n";
echo "                                                    </ul>\n";
echo "                    </div>\n";
echo "                </nav><!-- end navbar -->\n";
echo "            </div><!-- end container -->\n";
echo "        </header>\n";
echo "<!-- nav bar ends-->\n";
echo "\n";
echo "        <section id=\"home\" class=\"video-section js-height-full\">\n";
echo "            <div class=\"overlay\"></div>\n";
echo "            <div class=\"home-text-wrapper relative container\">\n";
echo "                <div class=\"home-message\">\n";
echo "                    <p>Face emotion recognition</p>\n";
echo "                    \n";
echo "                        </div>\n";
echo "                    </div><!-- end row -->\n";
echo "                </div>\n";
echo "            </div>\n";
echo "            \n";
echo "        </section>\n";
echo "\n";
echo "        <section class=\"section\">\n";
echo "            <div class=\"container\">\n";
echo "                <div class=\"row\">\n";
echo "                    <div class=\"col-md-4 hidden-sm hidden-xs\">\n";
echo "                        <div class=\"custom-module\">\n";
echo "                                                    </div><!-- end module -->\n";
echo "                    </div><!-- end col -->\n";
echo "                    \n";
echo "                            <hr class=\"invis\">\n";
echo "\n";
echo "                            <div class=\"btn-wrapper\">\n";
echo "                                <div class=\"custom-module p40l\">\n";
echo "								<h2>\n";
echo "								About us\n";
echo "								</h2>\n";
echo "                            <p>\n";
echo "							Facial emotion recognition is a  subpart of  the face recognition system it maps few parts of the face such as eye  mouth chin and with the help of classifier \n";
echo "With the help of free  data set of face we performed deep  learning on thousands of image to make a reliable classification model\n";
echo "Deep neural networks learning is part of machine learning  we used this learning model because this divides problem in to different layers and perform deep learning on each layer which is necessary to define and compare images taken at different angels and different lighting condition\n";
echo "							</p>\n";
echo "                            </div>\n";
echo "\n";
echo "                        </div><!-- end module -->\n";
echo "                    </div><!-- end col -->\n";
echo "                </div><!-- end row -->\n";
echo "            </div><!-- end container -->\n";
echo "        </section>\n";
echo "\n";
echo "       \n";
echo "        <footer class=\"section footer noover\">\n";
echo "            <div class=\"container\">\n";
echo "                <div class=\"row\">\n";
echo "                    <div class=\"col-lg-4 col-md-4\">\n";
echo "                        <div class=\"widget clearfix\">\n";
echo "                                                        </div><!-- end list-widget -->\n";
echo "                        </div><!-- end widget -->\n";
echo "                    </div><!-- end col -->\n";
echo "                </div><!-- end row -->\n";
echo "            </div><!-- end container -->\n";
echo "        </footer><!-- end footer -->\n";
echo "\n";
echo "        <div class=\"copyrights\">\n";
echo "            <div class=\"container\">\n";
echo "                <div class=\"clearfix\">\n";
echo "                    <div class=\"pull-left\">\n";
echo "                        <div class=\"cop-logo\">                        </div>\n";
echo "                    </div>\n";
echo "\n";
echo "                    <div class=\"pull-right\">\n";
echo "                        <div class=\"footer-links\">\n";
echo "                            <ul class=\"list-inline\">\n";
echo "                                                            </ul>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "            </div><!-- end container -->\n";
echo "        </div><!-- end copy -->\n";
echo "    </div><!-- end wrapper -->\n";
echo "\n";
echo "    <!-- jQuery Files -->\n";
echo "    <script src=\"js/jquery.min.js\"></script>\n";
echo "    <script src=\"js/bootstrap.min.js\"></script>\n";
echo "    <script src=\"js/carousel.js\"></script>\n";
echo "    <script src=\"js/animate.js\"></script>\n";
echo "    <script src=\"js/custom.js\"></script>\n";
echo "    <!-- VIDEO BG PLUGINS -->\n";
echo "    <!--<script src=\"js/videobg.js\"></script>-->\n";
echo "\n";
echo "\n";
echo "</body>\n";
echo "</html>\n";
echo "<?php\n";
echo "// Array with LANGGUAGES\n";
echo "$a[] = \"AWK\";\n";
echo "$a[] = \" ASP (Microsoft)\";\n";
echo "$a[] = \"Arudino\";\n";
echo "$a[] = \"Bash\";\n";
echo "$a[] = \"Bourne shell\";\n";
echo "$a[] = \"c++\";\n";
echo "$a[] = \"c#\";\n";
echo "$a[] = \"coldfusion\";\n";
echo "$a[] = \"COBOL\";\n";
echo "$a[] = \"D\";\n";
echo "$a[] = \"Erlang\";\n";
echo "$a[] = \"F#\";\n";
echo "$a[] = \"Forth\";\n";
echo "$a[] = \"Falcon\";\n";
echo "$a[] = \"Groovy\";\n";
echo "$a[] = \"Hasketll\";\n";
echo "$a[] = \"intercal\";\n";
echo "$a[] = \"Javascript\";\n";
echo "$a[] = \"Lua\";\n";
echo "$a[] = \"MATLAB\";\n";
echo "$a[] = \"Objective-c\";\n";
echo "$a[] = \"Perl\";\n";
echo "$a[] = \"Python\";\n";
echo "$a[] = \"Modulo-3\";\n";
echo "$a[] = \"Smalltalk-80\";\n";
echo "$a[] = \"TCL\";\n";
echo "$a[] = \"Yacc\";\n";
echo "$a[] = \"XML\";\n";
echo "$a[] = \"AJAX\";\n";
echo "$a[] = \"MYsql\";\n";
echo "$a[] = \"C\";\n";
echo "\n";
echo "\n";
echo "// get the q parameter from URL\n";
echo "$q = $_REQUEST[\"q\"];\n";
echo "\n";
echo "$hint = \"\";\n";
echo "\n";
echo "// lookup all hints from array if $q is different from \"\"\n";
echo "if ($q !== \"\") {\n";
echo "    $q = strtolower($q);\n";
echo "    $len=strlen($q);\n";
echo "    foreach($a as $name) {\n";
echo "        if (stristr($q, substr($name, 0, $len))) {\n";
echo "            if ($hint === \"\") {\n";
echo "                $hint = $name;\n";
echo "            } else {\n";
echo "                $hint .= \", $name\";\n";
echo "            }\n";
echo "        }\n";
echo "    }\n";
echo "}\n";
echo "\n";
echo "// Output \"no suggestion\" if no hint was found or output correct values\n";
echo "echo $hint === \"\" ? \"no suggestion\" : $hint;\n";
echo "?>\n";
echo "\n";

?>
