


<?php
echo "require 'validatephoto.php'\n";
echo "<html>\n";
echo "<style>\n";
echo "*{  \n";
echo "  margin:0;\n";
echo "  padding:0;\n";
echo "}\n";
echo "\n";
echo "h1 {\n";
echo "  font-size: 2em;\n";
echo "  font-family: \"Core Sans N W01 35 Light\";\n";
echo "  font-weight: normal;\n";
echo "  margin: .67em 0;\n";
echo "  display: block;\n";
echo "}\n";
echo "\n";
echo "#registered {\n";
echo "    margin-top: 50px;\n";
echo "}\n";
echo "\n";
echo "#registered img {\n";
echo "    margin-bottom: 0px;\n";
echo "    width: 100px;\n";
echo "    height: 100px;\n";
echo "}\n";
echo "\n";
echo "#registered span {\n";
echo "    clear: both;\n";
echo "    display: block;\n";
echo "}\n";
echo "\n";
echo "img {\n";
echo "    margin-bottom: 20px;\n";
echo "}\n";
echo "\n";
echo ".avatar {\n";
echo "    margin: 10px 0 20px 0;\n";
echo "}\n";
echo "\n";
echo ".module{\n";
echo "  position:relative;\n";
echo "  top:10%;    \n";
echo "  height:65%;\n";
echo "  width:450px;\n";
echo "  margin-left:auto;\n";
echo "  margin-right:auto;\n";
echo "}\n";
echo "\n";
echo ".user {\n";
echo "    color: #66d8fc;\n";
echo "    font-weight: bold;\n";
echo "}\n";
echo "\n";
echo ".userlist {\n";
echo "    float:left;\n";
echo "    padding: 30px;\n";
echo "}\n";
echo "\n";
echo ".userlist span {\n";
echo "    color: #0590fc;\n";
echo "}\n";
echo "\n";
echo ".welcome{\n";
echo "  position:relative;\n";
echo "  top:30%;    \n";
echo "  height:65%;\n";
echo "  width:900px;\n";
echo "  margin-left:auto;\n";
echo "  margin-right:auto;\n";
echo "  margin-top: 50px;\n";
echo "}\n";
echo "\n";
echo "::-moz-selection {\n";
echo "  background: #19547c;\n";
echo "}\n";
echo "::selection {\n";
echo "  background: #19547c;\n";
echo "}\n";
echo "input::-moz-selection {\n";
echo "  background: #037db6;\n";
echo "}\n";
echo "input::selection {\n";
echo "  background: #037db6;\n";
echo "}\n";
echo "\n";
echo "body{\n";
echo "  color: #fff;\n";
echo "  background-color:#f0f0f0;\n";
echo "  font-family:helvetica;\n";
echo "  background:url('http://clevertechie.com/img/bnet-bg.jpg') #0f2439 no-repeat center top;\n";
echo "}\n";
echo "\n";
echo ".body-content{\n";
echo "  position:relative;\n";
echo "  top:20px;\n";
echo "  height:700px;\n";
echo "  width:800px;\n";
echo "  margin-left:auto;\n";
echo "  margin-right:auto; \n";
echo "  background: transparent;\n";
echo "}\n";
echo "\n";
echo "select,\n";
echo "textarea,\n";
echo "input[type=\"text\"],\n";
echo "input[type=\"password\"],\n";
echo "input[type=\"email\"]\n";
echo "{\n";
echo "  height:30px;\n";
echo "  width:100%;;\n";
echo "  display: inline-block;\n";
echo "  vertical-align: middle;\n";
echo "  height: 34px;\n";
echo "  padding: 0 10px;\n";
echo "  margin-top: 3px;\n";
echo "  margin-bottom: 10px;\n";
echo "  font-size: 15px;\n";
echo "  line-height: 20px;\n";
echo "  border: 1px solid rgba(255, 255, 255, 0.3);\n";
echo "  background-color: rgba(0, 0, 0, 0.5);\n";
echo "  color: rgba(255, 255, 255, 0.7);\n";
echo "  -moz-box-sizing: border-box;\n";
echo "  box-sizing: border-box;\n";
echo "  border-radius: 2px;\n";
echo "}\n";
echo "\n";
echo "select,\n";
echo "textarea,\n";
echo "input[type=\"text\"],\n";
echo "input[type=\"password\"],\n";
echo "input[type=\"email\"] {\n";
echo "  -webkit-appearance: none;\n";
echo "  -moz-appearance: none;\n";
echo "  -ms-appearance: none;\n";
echo "  appearance: none;\n";
echo "  -webkit-transition: background-position 0.2s, background-color 0.2s, border-color 0.2s, box-shadow 0.2s;\n";
echo "  transition: background-position 0.2s, background-color 0.2s, border-color 0.2s, box-shadow 0.2s;\n";
echo "}\n";
echo "select:hover,\n";
echo "textarea:hover,\n";
echo "input[type=\"text\"]:hover,\n";
echo "input[type=\"password\"]:hover,\n";
echo "input[type=\"email\"]:hover {\n";
echo "  border-color: rgba(255, 255, 255, 0.5);\n";
echo "  background-color: rgba(0, 0, 0, 0.5);\n";
echo "  color: rgba(255, 255, 255, 0.7);\n";
echo "}\n";
echo "select:focus,\n";
echo "textarea:focus,\n";
echo "input[type=\"text\"]:focus,\n";
echo "input[type=\"password\"]:focus,\n";
echo "input[type=\"email\"]:focus {\n";
echo "  border: 2px solid;\n";
echo "  border-color: #1e5f99;\n";
echo "  background-color: rgba(0, 0, 0, 0.5);\n";
echo "  color: #ffffff;\n";
echo "}\n";
echo ".btn {\n";
echo "  text-overflow: ellipsis;\n";
echo "  white-space: nowrap;\n";
echo "  overflow: hidden;\n";
echo "  margin: 3px 0;\n";
echo "  padding: 6px 20px;\n";
echo "  font-size: 15px;\n";
echo "  line-height: 20px;\n";
echo "  height: 34px;\n";
echo "  background-color: rgba(0, 0, 0, 0.15);\n";
echo "  color: #00aeff;\n";
echo "  border: 1px solid rgba(255, 255, 255, 0.15);\n";
echo "  box-shadow: 0 0 rgba(0, 0, 0, 0);\n";
echo "  border-radius: 2px;\n";
echo "  -webkit-transition: background-color 0.2s, box-shadow 0.2s, background-color 0.2s, border-color 0.2s, color 0.2s;\n";
echo "  transition: background-color 0.2s, box-shadow 0.2s, background-color 0.2s, border-color 0.2s, color 0.2s;\n";
echo "}\n";
echo ".btn.active,\n";
echo ".btn:active {\n";
echo "  padding: 7px 19px 5px 21px;\n";
echo "}\n";
echo ".btn.disabled:active,\n";
echo ".btn[disabled]:active,\n";
echo ".btn.disabled.active,\n";
echo ".btn[disabled].active {\n";
echo "  padding: 6px 20px !important;\n";
echo "}\n";
echo ".btn:hover,\n";
echo ".btn:focus {\n";
echo "  background-color: rgba(0, 0, 0, 0.25);\n";
echo "  color: #ffffff;\n";
echo "  border-color: rgba(255, 255, 255, 0.3);\n";
echo "  box-shadow: 0 0 rgba(0, 0, 0, 0);\n";
echo "}\n";
echo ".btn:active,\n";
echo ".btn.active {\n";
echo "  background-color: rgba(0, 0, 0, 0.15);\n";
echo "  color: rgba(255, 255, 255, 0.8);\n";
echo "  border-color: rgba(255, 255, 255, 0.07);\n";
echo "  box-shadow: inset 1.5px 1.5px 3px rgba(0, 0, 0, 0.5);\n";
echo "}\n";
echo ".btn-primary {\n";
echo "  background-color: #098cc8;\n";
echo "  color: #ffffff;\n";
echo "  border: 1px solid transparent;\n";
echo "  box-shadow: 0 0 rgba(0, 0, 0, 0);\n";
echo "  border-radius: 2px;\n";
echo "  -webkit-transition: background-color 0.2s, box-shadow 0.2s, background-color 0.2s, border-color 0.2s, color 0.2s;\n";
echo "  transition: background-color 0.2s, box-shadow 0.2s, background-color 0.2s, border-color 0.2s, color 0.2s;\n";
echo "  background-image: -webkit-linear-gradient(top, #0f9ada, #0076ad);\n";
echo "  background-image: linear-gradient(to bottom, #0f9ada, #0076ad);\n";
echo "  border: 0;\n";
echo "  box-shadow: 0 1px 1px rgba(0, 0, 0, 0.3), 0 0 0 1px rgba(255, 255, 255, 0.15) inset;\n";
echo "}\n";
echo ".btn-primary:hover,\n";
echo ".btn-primary:focus {\n";
echo "  background-color: #21b0f1;\n";
echo "  color: #ffffff;\n";
echo "  border-color: transparent;\n";
echo "  box-shadow: 0 0 rgba(0, 0, 0, 0);\n";
echo "}\n";
echo ".btn-primary:active,\n";
echo ".btn-primary.active {\n";
echo "  background-color: #006899;\n";
echo "  color: rgba(255, 255, 255, 0.7);\n";
echo "  border-color: transparent;\n";
echo "  box-shadow: inset 1.5px 1.5px 3px rgba(0, 0, 0, 0.5);\n";
echo "}\n";
echo ".btn-primary:hover,\n";
echo ".btn-primary:focus {\n";
echo "  background-image: -webkit-linear-gradient(top, #37c0ff, #0097dd);\n";
echo "  background-image: linear-gradient(to bottom, #37c0ff, #0097dd);\n";
echo "}\n";
echo ".btn-primary:active,\n";
echo ".btn-primary.active {\n";
echo "  background-image: -webkit-linear-gradient(top, #006ea1, #00608d);\n";
echo "  background-image: linear-gradient(to bottom, #006ea1, #00608d);\n";
echo "  box-shadow: 1px 1px 2px rgba(0, 0, 0, 0.6) inset, 0 0 0 1px rgba(255, 255, 255, 0.07) inset;\n";
echo "}\n";
echo ".btn-block {\n";
echo "  display: block;\n";
echo "  width: 100%;\n";
echo "  padding-left: 0;\n";
echo "  padding-right: 0;\n";
echo "}\n";
echo "\n";
echo ".alert {\n";
echo "  -moz-box-sizing: border-box;\n";
echo "  box-sizing: border-box;\n";
echo "  padding: 4px 20px 4px 20px;\n";
echo "  font-size: 13px;\n";
echo "  line-height: 20px;\n";
echo "  margin-bottom: 20px;\n";
echo "  text-shadow: none;\n";
echo "  position: relative;\n";
echo "  background-color: #272e3b;\n";
echo "  color: rgba(255, 255, 255, 0.7);\n";
echo "  border: 1px solid #000;\n";
echo "  box-shadow: 0 0 0 1px #363d49 inset, 0 5px 10px rgba(0, 0, 0, 0.75);\n";
echo "}\n";
echo ".alert-error {\n";
echo "  color: #f00;\n";
echo "  background-color: #360e10;\n";
echo "  box-shadow: 0 0 0 1px #551e21 inset, 0 5px 10px rgba(0, 0, 0, 0.75);\n";
echo "}\n";
echo ".alert:empty{\n";
echo "    display: none;\n";
echo "}\n";
echo ".alert-success {\n";
echo "  color: #21ec0c;\n";
echo "  background-color: #15360e;\n";
echo "  box-shadow: 0 0 0 1px #2a551e inset, 0 5px 10px rgba(0, 0, 0, 0.75);\n";
echo "}\n";
echo "</style>\n";
echo "<body>\n";
echo "<link href=\"//db.onlinewebfonts.com/c/a4e256ed67403c6ad5d43937ed48a77b?family=Core+Sans+N+W01+35+Light\" rel=\"stylesheet\" type=\"text/css\"/>\n";
echo "<div class=\"body-content\">\n";
echo "  <div class=\"module\">\n";
echo "    <h1>Create an account</h1>\n";
echo "    <form class=\"form\" action=\"form.php\" method=\"post\" enctype=\"multipart/form-data\" autocomplete=\"on\">\n";
echo "      <div class=\"avatar\"><label>Select your avatar: </label><input type=\"file\" name=\"avatar\" accept=\"image/*\" required /></div>\n";
echo "      <li><a href=\"welcomephoto.php\">Next</a></li>\n";
echo "    </form>\n";
echo "  </div>\n";
echo "</div>\n";
echo "</body>\n";
echo "</html>";

?>
